### ISSUE TITLE
test/test.js.js 问题

### ISSUE THREAD

**Issue by Leotw** [dashnowords/Webpack4-Karma-Mocha-Chai-Demo#1]
karma.conf.js 内配的`files: 'test/test.js' ` 在执行`karma start`时成了`test/test.js.js` 
<img width="676" alt="wx20180901-225153 2x" src="https://user-images.githubusercontent.com/12053096/44947051-b05c2d80-ae39-11e8-8f6a-7c14375c1b3c.png">

**Comment by dashnowords** [comment]
你是运行的仓库里的工程吗？我重新试了一下，没能复现出你这个现象。

建议你可以按照如下方式尝试：
1.使用`yarn global add karma-cli`或`npm install -g karma-cli`来安装命令行工具
2.在项目目录下执行`npm run karma`或`yarn run karma`，对应的脚本已经写在`package.json`中

**Comment by Leotw** [comment]
@dashnowords 是的啊，我clone你的仓库，然后就按package.json脚本跑的，出现了test/test.js = test/test.js.js 跟node版本有关吗 
node:8.5.0
npm:5.7.1

**Comment by dashnowords** [comment]
我本地的是：
node:8.9.0  
npm:5.5.1 
这个应该是没关系的，你安装依赖用的`yarn`吗？仓库里有`yarn.lock`可以跟踪依赖包的版本

**Comment by Leotw** [comment]
用yarn安装是对的，测试用例也能跑起来。
为什么npm不行？

**Comment by dashnowords** [comment]
这个我也不清楚了 我试了一下自己本地 npm也是可以的，你那个截图的场景我还是第一次见

**Comment by Leotw** [comment]
@dashnowords 不过还是感谢朋友的demo了🙏 找到原因了咱们及时联系

**Comment by dashnowords** [comment]
好的 不客气

**Comment by Leotw** [comment]
已经找到问题了。
webpack4 如果配 karma-webpack@3.0.1(默认安装为3.0.1+)以上会有问题。把karma-webpack的版本写死成karma-webpack@3.0.0就OK了。再次感谢朋友～～

**Comment by dashnowords** [comment]
竟然是版本坑，这你都能发现也是很生猛，哈。
